[package]
name = "webnieuws-service"
version = "0.1.0"
authors = ["Ben Morrison <ben@gbmor.dev>"]
edition = "2018"

[dependencies]
chrono = "^0.4"
ctrlc = "^3.1"
lazy_static = "^1.4"
log = "^0.4"
rusqlite = "^0.20"
serde = "^1.0.99"
simplelog = "^0.7"
tokio = "^0.1.22"